name: Application Build - SOLVCON
on:
  schedule:
    - cron: '21 18 * * 5'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-18.04, macos-latest]
        fail-fast: false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Configure SSH
      if: matrix.os == 'disable'
      run: |
        ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ""
        chmod 700 ~/.ssh/
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
        ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
        ssh-keyscan -t rsa 127.0.0.1 >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        ls -al ~/.ssh/
        ssh localhost ls
        ssh 127.0.0.1 ls
    - name: Dependency (Ubuntu)
      if: matrix.os != 'macos-latest'
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qqy install fakeroot debhelper locales \
                libffi6 \
                liblapack3 liblapack-dev
    - name: Launch SOLVCON
      run: |
        source ${GITHUB_WORKSPACE}/scripts/init
        devenv add prime
        devenv use prime
        devenv show
        devenv launch solvcon
    - name: Show Dependency
      run: |
        source ${GITHUB_WORKSPACE}/scripts/init
        devenv use prime
        devenv show
        export
        which gcc
        gcc --version
        which cmake
        cmake --version
        which python3
        python3 --version
        python3 -c 'import numpy ; print("numpy.__version__:", numpy.__version__)'
        which gmsh
    - name: Show Python Env
      run: |
        source ${GITHUB_WORKSPACE}/scripts/init
        devenv use prime
        devenv show
        which python3
        python3 --version
        python3 -c 'import numpy ; print("numpy.__version__:", numpy.__version__)'
        python3 -c 'import sys ; print(sys.path)'
        echo "==============="
        echo "python globals:"
        python3 -c 'import numpy, solvcon ; print(globals())'
        echo "==============="
        echo "python locals:"
        python3 -c 'import numpy, solvcon ; print(locals())'
    - name: SOLVCON Function Test
      run: |
        source ${GITHUB_WORKSPACE}/scripts/init
        devenv use prime
        devenv show
        cd ${DEVENVCURRENTROOT}/application-solvcon/solvcon/
        make SC_PURE_PYTHON=1 test_from_package
